# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-30 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pedido_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo',
            field=models.IntegerField(default=1),
        ),
    ]
