# Generated by Django 2.1.1 on 2019-01-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190102_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Caja'),
        ),
    ]
