# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-30 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181130_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='precio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Precio'),
        ),
    ]
