# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181010_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
