# Generated by Django 2.1.1 on 2019-01-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_empleado_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='perfil',
            field=models.IntegerField(blank=True, choices=[(1, 'Administrador'), (2, 'Pedido'), (3, 'Almacen'), (4, 'Ventas'), (5, 'Repartidor')], default=2, null=True),
        ),
    ]
