# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-30 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cliente_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Almacen'),
        ),
    ]
