# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-12 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20181011_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
