# Generated by Django 2.1.1 on 2018-11-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_producto_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
