# Generated by Django 2.1.1 on 2019-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190123_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='precioCompra',
        ),
        migrations.AddField(
            model_name='producto_almacens',
            name='precioCompra',
            field=models.FloatField(null=True),
        ),
    ]
