# Generated by Django 2.1.1 on 2019-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190123_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='fechavencimiento',
            field=models.DateField(null=True),
        ),
    ]
