# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-24 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190123_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anulacionventa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
