# Generated by Django 2.1.1 on 2018-12-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='numeroSerie',
            field=models.CharField(max_length=3),
        ),
    ]
