# Generated by Django 2.1.1 on 2019-01-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190124_1131'),
        ('app', '0008_lote_fechavencimiento'),
    ]

    operations = [
    ]
