# Generated by Django 2.1.1 on 2019-01-30 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20190129_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipoventa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoventa', models.CharField(blank=True, max_length=45, null=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Venta')),
            ],
        ),
    ]
