# Generated by Django 2.1.1 on 2019-01-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tipoventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoventa',
            name='venta',
        ),
        migrations.AddField(
            model_name='tipoventa',
            name='venta',
            field=models.ManyToManyField(to='app.Venta'),
        ),
    ]
