# Generated by Django 2.1.1 on 2019-01-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tipoventa_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoventa',
            old_name='tipoventa',
            new_name='nombre',
        ),
    ]
