# Generated by Django 2.1.1 on 2019-01-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190130_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoventa',
            name='venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='tipoventa',
            field=models.ManyToManyField(to='app.Tipoventa'),
        ),
    ]
