# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-30 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190130_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
