# Generated by Django 2.1.7 on 2019-03-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cliente_email'),
        ('app', '0014_auto_20190130_1210'),
    ]

    operations = [
    ]
