# Generated by Django 2.1.7 on 2019-03-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20190308_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='repartidor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Empleado'),
            preserve_default=False,
        ),
    ]
